###Get all.
GET http://localhost:3000/transactions


###Post transaction.
POST http://localhost:3000/transactions
content-type: application/json

{
  "title": "Salario",
  "value" : 700,
  "type" : "income"
}
