###Get all.
GET http://localhost:3000/transactions


###Post transaction.
POST http://localhost:3000/transactions
content-type: application/json

{
  "title": "Comida",
  "value" : 600,
  "type" : "outcome"
}
